apiVersion: v1
kind: Service
metadata:
  name: fast-api-service
  namespace: fast-api-example
spec:
  selector:
    app: fast-api
  ports:
    - port: 8000
      targetPort: 8000
  type: LoadBalancer
