version: "3.8"
services:
  fastapi-app1:
    image: kennethan/fastapi-app:1.0.0-custom-lb
    expose:
      - 8000
    environment:
      - CONF_APP_NAME=app1

  fastapi-app2:
    image: kennethan/fastapi-app:1.0.0-custom-lb
    expose:
      - 8000
    environment:
      - CONF_APP_NAME=app2

  fastapi-app3:
    image: kennethan/fastapi-app:1.0.0-custom-lb
    expose:
      - 8000
    environment:
      - CONF_APP_NAME=app3

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - fastapi-app1
      - fastapi-app2
      - fastapi-app3
